### ISSUE TITLE
invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by vladciobancai** [oracle/oci-native-ingress-controller#10]
Hi,

Have deployed the OCI Native Ingress Controller on a OKE cluster using helm, configured the IngressClassParameters and IngressClass and then setup the ingress for an application and I'm getting the below error when tries to create the backend for a lb

```text
I0707 10:35:33.333667       1 ingress.go:219] "ensuring ingress" ingress="platform/keycloak-keycloakx"
I0707 10:35:33.499090       1 loadbalancer.go:171] Creating routing policy with request: {
 "name": "route_80",
 "conditionLanguageVersion": "V1",
 "rules": [
  {
   "name": "k8s_63604323a9",
   "condition": "all(http.request.headers[(i 'Host')] eq 'auth-preprod.domain.com' , http.request.url.path sw '/')",
   "actions": [
    {
     "name": "FORWARD_TO_BACKENDSET",
     "backendSetName": "bs_a6fbe8cb49de194"
    }
   ]
  }
 ],
 "LoadBalancerId": "ocid1.loadbalancer.oc1.me-jeddah-1.aaaaaaaarn5hbsa7h6rloqrwz5236xyiehu56p6ub2iftx7wojufvtlo6uaq",
 "OpcRequestId": null,
 "OpcRetryToken": null,
 "IfMatch": null,
 "RequestMetadata": {
  "RetryPolicy": null
 }
}
I0707 10:35:33.500818       1 ingress.go:262] "ip address already set on ingress" ingress="platform/keycloak-keycloakx" ipAddress="10.59.0.113"
I0707 10:35:33.500836       1 ingress.go:295] Processing ingress native-ic-ingress-private/keycloak-keycloakx
I0707 10:35:33.500841       1 ingressstate.go:84] Starting to build state for ingress class native-ic-ingress-private
I0707 10:35:33.500882       1 ingress.go:181] "Finished syncing ingress" ingress="platform/keycloak-keycloakx" duration="167.671995ms"
E0707 10:35:33.501107       1 runtime.go:79] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 275 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x1803ae0?, 0x296c720})
	/workspace/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:75 +0x99
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc000a2c120?})
	/workspace/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:49 +0x75
panic({0x1803ae0, 0x296c720})
	/usr/local/go/src/runtime/panic.go:884 +0x212
github.com/oracle/oci-native-ingress-controller/pkg/state.(*StateStore).BuildState(0xc0010efb88, 0xc0005f0a20)
	/workspace/pkg/state/ingressstate.go:96 +0x1e8
github.com/oracle/oci-native-ingress-controller/pkg/controllers/ingress.(*Controller).ensureIngress(0xc000e0f180, 0xc0006cc940, 0xc0005f0a20)
	/workspace/pkg/controllers/ingress/ingress.go:297 +0x1f6
github.com/oracle/oci-native-ingress-controller/pkg/controllers/ingress.(*Controller).sync(0xc000e0f180, {0xc000eb2020, 0x1b})
	/workspace/pkg/controllers/ingress/ingress.go:231 +0x9f6
github.com/oracle/oci-native-ingress-controller/pkg/controllers/ingress.(*Controller).processNextItem(0xc000e0f180)
	/workspace/pkg/controllers/ingress/ingress.go:159 +0x107
github.com/oracle/oci-native-ingress-controller/pkg/controllers/ingress.(*Controller).runWorker(0xc000e8d6a0?)
	/workspace/pkg/controllers/ingress/ingress.go:858 +0x25
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x2e39352e30?)
	/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:157 +0x3e
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x227b3a2265746174?, {0x1cc77e0, 0xc000e92120}, 0x1, 0xc000243680)
	/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:158 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x74736572222c6575?, 0x3b9aca00, 0x0, 0x67?, 0x312d68616464656a?)
	/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:135 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(0x6b6f2f6a35616476?, 0x63696c6275702d65?, 0x702d64756f6c632d?)
	/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:92 +0x25
created by github.com/oracle/oci-native-ingress-controller/pkg/controllers/ingress.(*Controller).Run
	/workspace/pkg/controllers/ingress/ingress.go:850 +0xfa
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1580a68]

goroutine 275 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc000a2c120?})
	/workspace/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:56 +0xd7
panic({0x1803ae0, 0x296c720})
	/usr/local/go/src/runtime/panic.go:884 +0x212
github.com/oracle/oci-native-ingress-controller/pkg/state.(*StateStore).BuildState(0xc0010efb88, 0xc0005f0a20)
	/workspace/pkg/state/ingressstate.go:96 +0x1e8
github.com/oracle/oci-native-ingress-controller/pkg/controllers/ingress.(*Controller).ensureIngress(0xc000e0f180, 0xc0006cc940, 0xc0005f0a20)
	/workspace/pkg/controllers/ingress/ingress.go:297 +0x1f6
github.com/oracle/oci-native-ingress-controller/pkg/controllers/ingress.(*Controller).sync(0xc000e0f180, {0xc000eb2020, 0x1b})
	/workspace/pkg/controllers/ingress/ingress.go:231 +0x9f6
github.com/oracle/oci-native-ingress-controller/pkg/controllers/ingress.(*Controller).processNextItem(0xc000e0f180)
	/workspace/pkg/controllers/ingress/ingress.go:159 +0x107
github.com/oracle/oci-native-ingress-controller/pkg/controllers/ingress.(*Controller).runWorker(0xc000e8d6a0?)
	/workspace/pkg/controllers/ingress/ingress.go:858 +0x25
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x2e39352e30?)
	/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:157 +0x3e
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x227b3a2265746174?, {0x1cc77e0, 0xc000e92120}, 0x1, 0xc000243680)
	/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:158 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x74736572222c6575?, 0x3b9aca00, 0x0, 0x67?, 0x312d68616464656a?)
	/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:135 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(0x6b6f2f6a35616476?, 0x63696c6275702d65?, 0x702d64756f6c632d?)
	/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:92 +0x25
created by github.com/oracle/oci-native-ingress-controller/pkg/controllers/ingress.(*Controller).Run
	/workspace/pkg/controllers/ingress/ingress.go:850 +0xfa
I0707 10:40:45.255653       1 main.go:112] starting controller runtime informers
```

```console
kubectl get pods -n native-ingress-controller-system --selector='app.kubernetes.io/name in (oci-native-ingress-controller)' -o wide                                                                                                                      130
NAME                                            READY   STATUS             RESTARTS         AGE    IP            NODE          NOMINATED NODE   READINESS GATES
oci-native-ingress-controller-98f5bccdd-55xvb   0/1     CrashLoopBackOff   23 (4m58s ago)   126m   10.59.1.97    10.59.2.171   <none>           <none>
oci-native-ingress-controller-98f5bccdd-h6f46   0/1     CrashLoopBackOff   23 (2m6s ago)    126m   10.59.1.192   10.59.2.127   <none>           <none>

kubectl get svc -n native-ingress-controller-system -o wide
NAME                            TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)   AGE    SELECTOR
oci-native-ingress-controller   ClusterIP   10.60.111.228   <none>        443/TCP   168m   app.kubernetes.io/instance=oci-native-ingress-controller,app.kubernetes.io/name=oci-native-ingress-controller

kubectl get ingress -n platform keycloak-keycloakx
NAME                 CLASS                       HOSTS                      ADDRESS       PORTS     AGE
keycloak-keycloakx   native-ic-ingress-private   auth-preprod.domain.com   10.59.0.113   80, 443   152m
```

Could somebody help us ?

**Comment by Inbaraj-S** [comment]
Could you please share details of your ingressclass.

**Comment by vladciobancai** [comment]
Below you can find the details

```text
apiVersion: "ingress.oraclecloud.com/v1beta1"
kind: IngressClassParameters
metadata:
  name: native-icp-private
  namespace: native-ingress-controller-system
spec:
  compartmentId: "ocid1.compartment.oc1......"
  subnetId: "ocid1.subnet.oc1.me-jeddah-1....."
  loadBalancerName: "ocinative-lb-private"
  isPrivate: true
  maxBandwidthMbps: 400
  minBandwidthMbps: 100
```

```text
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: native-ic-ingress-private
  annotations:
    ingressclass.kubernetes.io/is-default-class: "false"
spec:
  controller: oci.oraclecloud.com/native-ingress-controller
  parameters:
    scope: Namespace
    namespace: native-ingress-controller-system
    apiGroup: ingress.oraclecloud.com
    kind: ingressclassparameters
    name: native-icp-private
```

**Comment by Inbaraj-S** [comment]
Do you have multiple ingressclass's? If not, make sure your ingress has the classname set to `native-ic-ingress-private`.
If not then setting this: ```ingressclass.kubernetes.io/is-default-class: "false"``` will not help create backend successful since there will not be any default ingressclass to map to.

**Comment by vladciobancai** [comment]
We have another ingressclass  configured, called`nginx` that is setup as default, this is why we setup the `native-ic-ingress-private` to do not be the default one.
 For example, for keycloakx app we have setup in the helm value file the following `ingress.ingressClassName: native-ic-ingress-private` where we can see the lb is created but the backend is not added/configured. After that the pods from oci-native-ingress-controller throw the errors from the first post.

```console
kubectl get ingress -n platform keycloak-keycloakx
NAME                 CLASS                       HOSTS                      ADDRESS       PORTS     AGE
keycloak-keycloakx   native-ic-ingress-private   auth-preprod.domain.com   10.59.0.113   80, 443   152m
```

We can not delete the ingressclass `nginx` to leave only the ingressclass `native-ic-ingress-private`

**Comment by Inbaraj-S** [comment]
Thank you for your inputs, will look into it and get back.

**Comment by Inbaraj-S** [comment]
@vladciobancai 
This is fixed as part of Release V1.3, can you check and confirm.
